package de.flockiix.flockbot.core.sql;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.sql.*;

public class SQLConnector {
    private static final Logger LOGGER = LoggerFactory.getLogger(SQLConnector.class);

    private Connection connection;
    private Statement statement;

    public SQLConnector() {
        connect();
        createTables();
    }

    private boolean isConnected() {
        return connection != null;
    }

    /**
     * Connects to the SQLite database or creates it if not existing.
     */
    private void connect() {
        if (!isConnected()) {
            try {
                File file = new File("database.db");

                if (!file.exists()) {
                    file.createNewFile();
                }

                String url = "jdbc:sqlite:" + file.getPath();
                connection = DriverManager.getConnection(url);
                statement = connection.createStatement();

                LOGGER.info("Connection to the database established");
            } catch (SQLException | IOException exception) {
                exception.printStackTrace();
            }
        }
    }

    /**
     * Closes the connection to the database.
     */
    public void close() {
        if (isConnected()) {
            try {
                connection.close();
                LOGGER.info("Disconnected from database");
            } catch (SQLException exception) {
                exception.printStackTrace();
            }
        }
    }

    /**
     * @param sql the sql query
     * @return the ResultSet object generated by the query
     */
    public ResultSet query(String sql) {
        try {
            if (isConnected()) {
                return statement.executeQuery(sql);
            }
        } catch (SQLException exception) {
            exception.printStackTrace();
        }

        return null;
    }

    /**
     * Executes the sql query on the database.
     *
     * @param sql the sql query
     */
    public void update(String sql) {
        try {
            statement.execute(sql);
        } catch (SQLException exception) {
            exception.printStackTrace();
        }
    }

    /**
     * Creates all tables.
     */
    private void createTables() {
        createTable("CREATE TABLE IF NOT EXISTS Prefixes (GUILDID VARCHAR(30), PREFIX VARCHAR(5));");
        createTable("CREATE TABLE IF NOT EXISTS Newsletter (USERID VARCHAR(30), SUBSCRIBED BOOLEAN);");
        createTable("CREATE TABLE IF NOT EXISTS Blacklist (GUILDID VARCHAR(30), WORD VARCHAR(30));");
        createTable("CREATE TABLE IF NOT EXISTS Warnings (GUILDID VARCHAR(30), USERID VARCHAR(30), WARNINGS INTEGER);");
        LOGGER.info("Tables created");
    }

    /**
     * Creates a table.
     *
     * @param sql the sql query to create the table
     */
    private void createTable(String sql) {
        try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            preparedStatement.executeUpdate();
        } catch (SQLException exception) {
            exception.printStackTrace();
        }
    }
}
